export const mokTransactions: Transaction[] = [
    {
        id: '1',
        $id: '1',
        transaction_id: '1',
        accountId: 'account_1',
        amount: 100.0,
        date: '2023-10-01',
        name: 'Grocery Store',
        category: ['Travel'],
        pending: false,
        paymentChannel: 'Credit Card',
        type: 'credit',
        status: 'Success',
        image: '',
        $createdAt: '',
        channel: '',
        senderBankId: '',
        receiverBankId: ''
    },
    {
        id: '2',
        $id: '2',
        transaction_id: '2',
        accountId: 'account_2',
        amount: 50.0,
        date: '2023-10-02',
        name: 'Coffee Shop',
        category: ['Payment'],
        status: 'Success',
        pending: false,
        paymentChannel: 'Debit Card',
        type: 'debit',
        image: '',
        $createdAt: '',
        channel: '',
        senderBankId: '',
        receiverBankId: ''
    },
    {
        id: '3',
        $id: '3',
        transaction_id: '3',
        accountId: 'account_3',
        amount: 200.0,
        status: 'Success',
        date: '2023-10-03',
        name: 'Electronics Store',
        category: ['Food and Drink'],
        pending: false,
        paymentChannel: 'Credit Card',
        type: 'credit',
        image: '',
        $createdAt: '',
        channel: '',
        senderBankId: '',
        receiverBankId: ''
    },
    {
        id: '4',
        $id: '4',
        transaction_id: '4',
        accountId: 'account_4',
        status: 'Success',
        amount: 75.0,
        date: '2023-10-04',
        name: 'Restaurant',
        category: ['Food'],
        pending: false,
        paymentChannel: 'Credit Card',
        type: 'debit',
        image: '',
        $createdAt: '',
        channel: '',
        senderBankId: '',
        receiverBankId: ''
    },
    {
        id: '5',
        $id: '5',
        transaction_id: '5',
        accountId: 'account_5',
        status: 'Success',
        amount: 150.0,
        date: '2023-10-05',
        name: 'Clothing Store',
        category: ['Shopping'],
        pending: false,
        paymentChannel: 'Debit Card',
        type: 'credit',
        image: '',
        $createdAt: '',
        channel: '',
        senderBankId: '',
        receiverBankId: ''
    },
    {
        id: '6',
        $id: '6',
        transaction_id: '6',
        accountId: 'account_6',
        amount: 120.0,
        status: 'Success',
        date: '2023-10-06',
        name: 'Gas Station',
        category: ['Fuel'],
        pending: false,
        paymentChannel: 'Credit Card',
        type: 'debit',
        image: '',
        $createdAt: '',
        channel: '',
        senderBankId: '',
        receiverBankId: ''
    }
]
